server:
    port: 8082
spring:
  application:
    name: useree-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chiyu?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: root
mybatis-plus:
  type-aliases-package: com.chiyu.domin
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chiyu: debug

